<?php

namespace shop\entities\shop;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "shop_characteristics".
 *
 * @property int $id
 * @property string $name
 * @property string $type
 * @property bool $required
 * @property string $default
 * @property string $json_variants
 * @property int $sort
 */
class Characteristic extends ActiveRecord
{
    const TYPE_STRING = 'string';
    const TYPE_INTEGER = 'integer';
    const TYPE_FLOAT = 'float';

    public $variants;


    public static function create($name, $type, $required, $default, array $variants, $sort) : self
    {
        $characteristic = new self();
        $characteristic->name = $name;
        $characteristic->type = $type;
        $characteristic->required = $required;
        $characteristic->default = $default;
        $characteristic->variants = $variants;
        $characteristic->sort = $sort;

        return $characteristic;
    }

    public function edit($name, $type, $required, $default, array $variants, $sort) : void
    {
        $this->name = $name;
        $this->type = $type;
        $this->required = $required;
        $this->default = $default;
        $this->variants = $variants;
        $this->sort = $sort;
    }

    public static function isVariants()
    {
        return [
            self::TYPE_STRING => 'string',
            self::TYPE_INTEGER => 'integer',
            self::TYPE_FLOAT => 'float'
        ];
    }

    public function isSelect()
    {
        return count($this->variants) > 0;
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'shop_characteristics';
    }

    public function isString()
    {
        return $this->type === self::TYPE_STRING;
    }

    public function isInteger()
    {
        return $this->type === self::TYPE_INTEGER;
    }

    public function isFloat()
    {
        return $this->type === self::TYPE_FLOAT;
    }


    public function beforeSave($insert)
    {
        $this->setAttribute('json_variants',$this->variants);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->variants = $this->getAttribute('json_variants');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
